import {z} from "zod";
import {api,body,getProject,saveProject,bucket,AppError} from "@/lib/inspection/store";
import {createHash} from "node:crypto";
const SERVICE="https://imagery.nationalmap.gov/arcgis/rest/services/USGSNAIPImagery/ImageServer";
type C={params:Promise<{id:string}>};
async function remote(url:string){const response=await fetch(url,{signal:AbortSignal.timeout(25000),headers:{Accept:"application/json"}});if(!response.ok)throw new AppError(502,`The public imagery service is unavailable (HTTP ${response.status}). You can retry or skip the aerial intro.`);return response}
async function data(url:string){const value=await(await remote(url)).json() as any;if(value.error)throw new AppError(502,"The imagery provider could not return this location. Retry or skip the aerial intro.");return value}
export const POST=(req:Request,c:C)=>api(req,async()=>{const v=await body(req,z.object({action:z.enum(["prepare","confirm","remove"]),revision:z.number().int(),latitude:z.number().min(24).max(50).optional(),longitude:z.number().min(-125).max(-66).optional()}));const p=await getProject((await c.params).id);if(v.revision!==p.revision)throw new AppError(409,"The inspection changed. Refresh before updating the aerial intro.");if(v.action==="remove")return Response.json({project:await saveProject({...p,aerial:null},p.revision)});if(v.action==="confirm"){if(!p.aerial)throw new AppError(409,"Preview the location first.");return Response.json({project:await saveProject({...p,aerial:{...p.aerial,status:"confirmed"}},p.revision)})}
let latitude=v.latitude,longitude=v.longitude,matchedAddress=p.aerial?.matchedAddress||p.address;if(latitude===undefined||longitude===undefined){const q=new URLSearchParams({address:p.address,benchmark:"Public_AR_Current",format:"json"});const geo=await data("https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?"+q);const match=geo.result?.addressMatches?.[0];if(!match)throw new AppError(422,"No address match was found. Use a complete contiguous-US address, or skip the aerial intro.");longitude=Number(match.coordinates.x);latitude=Number(match.coordinates.y);matchedAddress=String(match.matchedAddress)}if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||latitude!<24||latitude!>50||longitude!< -125||longitude!> -66)throw new AppError(422,"Aerial coverage is currently limited to the contiguous United States.");
const query=new URLSearchParams({f:"json",where:"1=1",geometry:`${longitude},${latitude}`,geometryType:"esriGeometryPoint",inSR:"4326",spatialRel:"esriSpatialRelIntersects",outFields:"OBJECTID,Year,acquisition_date,resolution_value",returnGeometry:"false",orderByFields:"Year DESC",resultRecordCount:"5"});const catalog=await data(SERVICE+"/query?"+query);const item=catalog.features?.[0]?.attributes;if(!item?.OBJECTID)throw new AppError(422,"No aerial imagery covers this location. The package can be generated without an aerial intro.");const x=longitude!*20037508.342789244/180;const y=Math.log(Math.tan((90+latitude!)*Math.PI/360))*20037508.342789244/Math.PI;const half=480;const qs=new URLSearchParams({f:"json",bbox:`${x-half},${y-half},${x+half},${y+half}`,bboxSR:"3857",imageSR:"3857",size:"2048,2048",format:"jpg",renderingRule:JSON.stringify({rasterFunction:"NaturalColor"}),mosaicRule:JSON.stringify({mosaicMethod:"esriMosaicLockRaster",lockRasterIds:[item.OBJECTID]})});const result=await data(SERVICE+"/exportImage?"+qs);if(!result.href||!result.extent)throw new AppError(502,"No aerial image was returned.");const imageUrl=new URL(result.href);if(imageUrl.origin!=="https://imagery.nationalmap.gov"||!imageUrl.pathname.startsWith("/arcgis/rest/directories/imagery_output/"))throw new AppError(502,"The imagery service returned an unexpected image address.");const response=await remote(imageUrl.href);const bytes=await response.arrayBuffer();if(bytes.byteLength<1000||bytes.byteLength>8*1024*1024||new Uint8Array(bytes)[0]!==255||new Uint8Array(bytes)[1]!==216)throw new AppError(502,"The aerial image failed validation.");const imageKey=`${p.id}/aerial/${crypto.randomUUID()}.jpg`;await bucket().put(imageKey,bytes,{httpMetadata:{contentType:"image/jpeg"}});const year=String(item.Year||"Acquisition year unavailable");const aerial={status:"draft" as const,latitude:latitude!,longitude:longitude!,matchedAddress,year,attribution:"USGS / USDA NAIP. Data available from U.S. Geological Survey, National Geospatial Program.",imageKey,imageSha256:createHash("sha256").update(new Uint8Array(bytes)).digest("hex"),extent:{xmin:result.extent.xmin,ymin:result.extent.ymin,xmax:result.extent.xmax,ymax:result.extent.ymax},rasterId:Number(item.OBJECTID)};try{return Response.json({project:await saveProject({...p,aerial},p.revision)})}catch(e){await bucket().delete(imageKey);throw e}
});
export const GET=(req:Request,c:C)=>api(req,async()=>{const p=await getProject((await c.params).id);if(!p.aerial)throw new AppError(404,"No aerial preview exists.");const image=await bucket().get(p.aerial.imageKey);if(!image)throw new AppError(404,"The saved aerial preview is unavailable.");return new Response(image.body,{headers:{"Content-Type":"image/jpeg"}})});
