# docker compose -f compose.yaml -f compose.secrets.yaml up -d --build
services:
  app:
    environment:
      OPENAI_API_KEY: ""
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
    secrets:
      - openai_api_key
secrets:
  openai_api_key:
    file: ./secrets/openai_api_key
