"use client";
import {useEffect,useState} from "react";
import {MapPin,LoaderCircle,Check} from "lucide-react";
import type {Inspection} from "@/lib/inspection/types";
export default function AerialCard({project:p,disabled,onSaved,onError}:{project:Inspection;disabled:boolean;onSaved:()=>Promise<unknown>;onError:(s:string)=>void}){const [busy,setBusy]=useState(false),[latitude,setLatitude]=useState(""),[longitude,setLongitude]=useState("");const a=p.aerial;useEffect(()=>{setLatitude(a?.latitude.toFixed(6)||"");setLongitude(a?.longitude.toFixed(6)||"")},[a?.imageKey]);const moved=!!a&&(Math.abs(Number(latitude)-a.latitude)>0.000002||Math.abs(Number(longitude)-a.longitude)>0.000002);
async function action(action:string,adjust=false){setBusy(true);try{const r=await fetch(`/api/projects/${p.id}/aerial`,{method:"POST",headers:{"Content-Type":"application/json","X-Inspection-Request":"1"},body:JSON.stringify({action,revision:p.revision,...(adjust?{latitude:Number(latitude),longitude:Number(longitude)}:{})})});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);await onSaved()}catch(e){onError((e as Error).message)}finally{setBusy(false)}}
function point(e:React.MouseEvent<HTMLButtonElement>){if(!a)return;const r=e.currentTarget.getBoundingClientRect();const x=a.extent.xmin+(e.clientX-r.left)/r.width*(a.extent.xmax-a.extent.xmin);const y=a.extent.ymax-(e.clientY-r.top)/r.height*(a.extent.ymax-a.extent.ymin);setLongitude((x/20037508.342789244*180).toFixed(6));setLatitude((Math.atan(Math.exp(y/20037508.342789244*Math.PI))*360/Math.PI-90).toFixed(6))}
let marker={left:"50%",top:"50%"};if(a&&latitude&&longitude){const x=Number(longitude)*20037508.342789244/180;const y=Math.log(Math.tan((90+Number(latitude))*Math.PI/360))*20037508.342789244/Math.PI;marker={left:`${(x-a.extent.xmin)/(a.extent.xmax-a.extent.xmin)*100}%`,top:`${(a.extent.ymax-y)/(a.extent.ymax-a.extent.ymin)*100}%`}}
return <article className="thread-card aerial-card"><details><summary><MapPin size={17}/><span>Aerial opening <small>{a?.status==="confirmed"?"Location confirmed":"Optional"}</small></span></summary><p>Open the recap with real historical aerial imagery, a zoom and gentle overhead rotation. This is a 2D animation. Imagery is available for the contiguous US.</p>{!a?<button className="btn small" disabled={disabled||busy} onClick={()=>action("prepare")}>{busy?<LoaderCircle className="spin"/>:<MapPin/>}Find the property</button>:<><p className="aerial-match">{a.matchedAddress} · {a.year}</p><button className="aerial-preview" disabled={disabled||busy} onClick={point} aria-label="Select the property location on the aerial preview"><img src={`/api/projects/${p.id}/aerial?image=${a.imageSha256}`} alt="Historical aerial imagery of the matched address"/><span className="property-marker" style={marker}><MapPin size={26}/></span></button><p className="aerial-hint">Confirm the correct building. Address matches can land near the road. Tap the building or adjust the coordinates, then update the preview.</p><div className="form-grid"><label>Latitude<input inputMode="decimal" value={latitude} onChange={e=>setLatitude(e.target.value)} aria-label="Property latitude"/></label><label>Longitude<input inputMode="decimal" value={longitude} onChange={e=>setLongitude(e.target.value)} aria-label="Property longitude"/></label></div><div className="inline-actions">{moved?<button className="btn small" disabled={disabled||busy} onClick={()=>action("prepare",true)}>{busy?<LoaderCircle className="spin"/>:<MapPin/>}Update preview</button>:<button className="btn small primary" disabled={disabled||busy||a.status==="confirmed"} onClick={()=>action("confirm")}><Check/>{a.status==="confirmed"?"Property location confirmed":"Confirm property location"}</button>}<button className="text-btn" disabled={disabled||busy} onClick={()=>action("remove")}>Skip aerial intro</button></div><small className="aerial-credit">{a.attribution} Acquisition year: {a.year}. Historical location context, not current inspection evidence.</small></>}</details></article>
}
