"use client";
import AuthGate from "./auth-gate";
import AerialCard from "./aerial-card";
import {useCallback,useEffect,useRef,useState} from "react";
import {House,Plus,Upload,Film,FileText,MessageSquare,Check,ShieldCheck,Clock,Send,LoaderCircle,Play,Download,AlertCircle,ChevronDown,Settings2,X,RefreshCw,CheckCheck,PanelRightClose,Video,Scissors,FolderOpen} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from "@/components/ui/dialog";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Checkbox} from "@/components/ui/checkbox";
import {Switch} from "@/components/ui/switch";
import {Progress} from "@/components/ui/progress";
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from "@/components/ui/empty";
import {Toaster,toast} from "sonner";
import type {Inspection,Finding,ProjectDetail,Job} from "@/lib/inspection/types";
import {timestamp,MAX_VIDEO_BYTES,UPLOAD_PART_BYTES} from "@/lib/inspection/types";

async function request<T=Record<string,unknown>>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,keepalive:url.startsWith("/api/jobs/")&&init?.method==="POST",headers:{...init?.headers,"X-Inspection-Request":"1"}});let d: any;try{d=await r.json()}catch{throw new Error("The server could not respond. Please retry.")}if(!r.ok){if(r.status===401)window.dispatchEvent(new Event("inspection-session-expired"));throw new Error(d.error||"The request failed.");}return d}
const json=(method:string,data:unknown)=>({method,headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
const size=(n:number)=>`${(n/1048576).toFixed(1)} MiB`;
const today=()=>new Date().toISOString().slice(0,10);
const initialFinding=():Finding=>({id:crypto.randomUUID(),title:"",location:"",observation:"",evidence:"",whyItMatters:"",recommendation:"",severity:"maintenance",timestamp:0,endTimestamp:5,confidence:"Inspector observation",decision:"pending",pointer:null,diagram:null});

function InspectionStudio({account,onLogout}:{account:{id:string;username:string};onLogout:()=>void}){
 const [projects,setProjects]=useState<Inspection[]>([]),[detail,setDetail]=useState<ProjectDetail|null>(null),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 const [newOpen,setNewOpen]=useState(false),[address,setAddress]=useState(""),[inspector,setInspector]=useState(""),[date,setDate]=useState(today()),[busy,setBusy]=useState(""),[tab,setTab]=useState("footage"),[uploadPct,setUploadPct]=useState<number|null>(null),[drag,setDrag]=useState(false),[notes,setNotes]=useState(""),[chat,setChat]=useState(""),[chatOpen,setChatOpen]=useState(true),[edit,setEdit]=useState<Finding|null>(null),[filter,setFilter]=useState("all"),[runtime,setRuntime]=useState<{configured:boolean;model:string}|null>(null),[previewFile,setPreviewFile]=useState<string|null>(null);
 const [narration,setNarration]=useState<{hash:string;scenes:{key:string;text:string}[]}|null>(null),[approvedHash,setApprovedHash]=useState("");
 const [online,setOnline]=useState(true);useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();addEventListener("online",update);addEventListener("offline",update);return()=>{removeEventListener("online",update);removeEventListener("offline",update)}},[]);
 const [pendingFile,setPendingFile]=useState<File|null>(null),[initialNotes,setInitialNotes]=useState(""),[evidenceTime,setEvidenceTime]=useState<number|null>(null);
 const selection=useRef<string|null>(null),notesLatest=useRef("");selection.current=selected;notesLatest.current=notes;
 const fileInput=useRef<HTMLInputElement>(null),video=useRef<HTMLVideoElement>(null),polling=useRef(false),notesDirty=useRef(false);
 const p=detail?.project;const active=detail?.jobs.find(j=>j.status==="starting"||j.status==="running");const approved=p?.findings.filter(f=>f.decision==="approved")||[];const pending=p?.findings.filter(f=>f.decision==="pending")||[];
 const loadList=useCallback(async()=>{const d=await request<{projects:Inspection[]}>("/api/projects");setProjects(d.projects);return d.projects},[]);
 const refresh=useCallback(async(id:string)=>{const d=await request<ProjectDetail>(`/api/projects/${id}`);if(selection.current===id){setDetail(d);if(!notesDirty.current)setNotes(d.project.notes);}return d},[]);
 useEffect(()=>{void request<{configured:boolean;model:string}>("/api/runtime").then(setRuntime).catch(()=>setRuntime(null));loadList().then(list=>{const id=new URLSearchParams(location.search).get("inspection");setSelected(list.some(q=>q.id===id)?id:list[0]?.id||null)}).catch(e=>setLoadError(e.message)).finally(()=>setLoading(false))},[loadList]);
 useEffect(()=>{if(!selected){setDetail(null);return}setLoading(true);setDetail(null);setEdit(null);setChat("");notesDirty.current=false;refresh(selected).then(()=>{setLoadError("");history.replaceState(null,"",`?inspection=${selected}`)}).catch(e=>setLoadError(e.message)).finally(()=>setLoading(false))},[selected,refresh]);
 useEffect(()=>{if(!selected||!active)return;const id=active.id;const tick=async()=>{if(polling.current)return;polling.current=true;try{await request(`/api/jobs/${id}`,json("POST",{action:"poll"}));await refresh(selected);await loadList()}catch(e){toast.error((e as Error).message,{id:"poll-error"})}finally{polling.current=false}};const timer=setInterval(tick,6000);return()=>clearInterval(timer)},[selected,active?.id,refresh,loadList]);
 useEffect(()=>{let valid=true;setApprovedHash("");setNarration(null);if(p)request<{hash:string;scenes:{key:string;text:string}[];revision:number}>(`/api/projects/${p.id}/narration`).then(n=>{if(valid&&n.revision===p.revision)setNarration(n)}).catch(()=>{});return()=>{valid=false}},[p?.id,p?.revision]);
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts:unknown)=>void}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{ctx.registerTool({name:"read_inspection_summary",description:"Read the selected inspection and its review status without changing it.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{if(!selected)return {selected:false};const d=await refresh(selected);return {id:d.project.id,address:d.project.address,findings:d.project.findings,coverage:d.project.coverage,activeJobs:d.jobs.filter(j=>j.status==="running"||j.status==="starting").map(j=>({id:j.id,status:j.status,phase:j.phase}))}}},{signal:lifecycle.signal});ctx.registerTool({name:"add_inspector_note",description:"Append and persist an inspector-provided note to the selected inspection. Does not approve findings.",inputSchema:{type:"object",properties:{note:{type:"string",minLength:1,maxLength:3000}},required:["note"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const note=(input as {note?:unknown})?.note;if(typeof note!=="string"||!note.trim()||note.length>3000)throw new Error("Provide a nonempty note up to 3000 characters.");if(!selected)throw new Error("Select an inspection first.");if(notesDirty.current)throw new Error("Save the existing draft before appending a note.");const d=await refresh(selected);await request(`/api/projects/${selected}`,json("PATCH",{revision:d.project.revision,notes:[d.project.notes,note.trim()].filter(Boolean).join("\n\n")}));const updated=await refresh(selected);return {id:selected,saved:true,revision:updated.project.revision}}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[selected,refresh]);
 async function task(label:string,fn:()=>Promise<void>){if(!navigator.onLine){toast.error("Reconnect to save changes or process this inspection.");return}setBusy(label);try{await fn()}catch(e){toast.error((e as Error).message);if(selected)await refresh(selected).catch(()=>{})}finally{setBusy("")}}
 async function create(){await task("create",async()=>{const r=await request<{project:Inspection}>("/api/projects",json("POST",{address,inspector,date,notes:initialNotes}));setProjects(v=>[r.project,...v]);selection.current=r.project.id;setSelected(r.project.id);setDetail({project:r.project,jobs:[],files:[]});setNewOpen(false);setAddress("");setTab("footage");toast.success("Inspection created");if(pendingFile)await upload(pendingFile,r.project);setPendingFile(null);setInitialNotes("")})}
 async function upload(file?:File,project:Inspection|undefined=p){const p=project;if(!p||!file)return;if(file.size>MAX_VIDEO_BYTES){toast.error("Choose a video up to 1 GiB. Export larger footage at a lower bitrate.");return}if(!["video/mp4","video/quicktime","video/webm"].includes(file.type)){toast.error("Choose an MP4, MOV, or WebM video.");return}setUploadPct(0);try{
 const sampled=new Uint8Array(await new Blob([file.slice(0,65536),file.slice(Math.max(0,file.size-65536)),String(file.size)]).arrayBuffer());const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",sampled))).map(v=>v.toString(16).padStart(2,"0")).join("");
 const init=await request<{project:Inspection}>(`/api/projects/${p.id}/upload`,json("POST",{action:"start",name:file.name,type:file.type,size:file.size,fingerprint}));const done=new Set(init.project.video?.parts?.map(v=>v.partNumber)||[]);
 for(let offset=0,part=1;offset<file.size;offset+=UPLOAD_PART_BYTES,part++){const end=Math.min(offset+UPLOAD_PART_BYTES,file.size);if(done.has(part)){setUploadPct(Math.round(end/file.size*100));continue}await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("PUT",`/api/projects/${p.id}/upload?part=${part}`);xhr.setRequestHeader("Content-Type","application/octet-stream");xhr.setRequestHeader("X-Part-Size",String(end-offset));xhr.setRequestHeader("X-Inspection-Request","1");xhr.timeout=120000;xhr.ontimeout=()=>reject(new Error("Upload timed out. Select the same video to resume."));xhr.upload.onprogress=e=>{if(e.lengthComputable)setUploadPct(Math.round((offset+e.loaded)/file.size*100))};xhr.onerror=()=>reject(new Error("Upload interrupted. Select the same video to resume."));xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)resolve();else{let message="Upload could not finish. Select the same video to resume.";try{message=JSON.parse(xhr.responseText).error||message}catch{}reject(new Error(message))}};xhr.send(file.slice(offset,end))})}
 await request(`/api/projects/${p.id}/upload`,json("POST",{action:"complete"}));await refresh(p.id);await loadList();toast.success("Walkthrough saved")
 }catch(e){toast.error((e as Error).message)}finally{setUploadPct(null);if(fileInput.current)fileInput.current.value=""}}
 async function saveNotes(){if(!p)return;const submitted=notes;await task("notes",async()=>{await request(`/api/projects/${p.id}`,json("PATCH",{revision:p.revision,notes:submitted}));if(notesLatest.current===submitted)notesDirty.current=false;await refresh(p.id);toast.success("Details saved")})}
 async function startJob(kind:string,message?:string){if(!p)return;await task(kind,async()=>{if(notesDirty.current){const r=await request<{project:Inspection}>(`/api/projects/${p.id}`,json("PATCH",{revision:p.revision,notes}));setDetail(d=>d?{...d,project:r.project}:d);notesDirty.current=false;}await request(`/api/projects/${p.id}/jobs`,json("POST",{kind,message,requestId:crypto.randomUUID(),narrationHash:kind==="export"?narration?.hash:undefined}));if(kind==="chat")setChat("");if(kind==="analysis")setTab("review");if(kind==="export")setTab("delivery");await refresh(p.id)})}
 async function saveFinding(f:Finding){if(!p)return;await task("finding",async()=>{await request(`/api/projects/${p.id}/findings`,json("POST",{revision:p.revision,finding:f}));setEdit(null);await refresh(p.id);toast.success(f.decision==="approved"?"Finding approved":"Finding saved")})}
 function seek(t:number){setEvidenceTime(t)}
 async function sendContext(){if(!p||!chat.trim())return;if(p.coverage){await startJob("chat",chat);return}const message=chat.trim();await task("context",async()=>{await request(`/api/projects/${p.id}`,json("PATCH",{revision:p.revision,notes:[p.notes,message].filter(Boolean).join("\n\n")}));setChat("");await refresh(p.id);toast.success("Context saved for analysis")})}
 const createFields=<><label>Property address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Street, city, state and ZIP" maxLength={200}/></label><label className="intake-file"><Upload size={22}/><span>{pendingFile?pendingFile.name:"Choose your walkthrough video"}<small>MP4, MOV or WebM · Up to 1 GiB / 90 minutes</small></span><input type="file" accept="video/mp4,video/quicktime,video/webm" onChange={e=>setPendingFile(e.target.files?.[0]||null)} aria-label="Intake walkthrough video"/></label><div className="form-grid"><label>Inspector<input value={inspector} onChange={e=>setInspector(e.target.value)} placeholder="Your name" maxLength={100}/></label><label>Inspection date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label>Anything we should know?<textarea value={initialNotes} onChange={e=>setInitialNotes(e.target.value)} rows={3} maxLength={15000} placeholder="Rooms covered, measurements, or concerns to look at…"/></label><button className="btn primary" disabled={!address.trim()||!!busy} onClick={create}>{busy==="create"?<LoaderCircle className="spin"/>:<Plus/>}Start inspection</button></>;
 const files=detail?.files.filter(f=>f.kind==="export")||[];
 const latest=detail?.jobs[0];
 const progress=(kind:string)=><>{active?.kind===kind&&<div className="thread-status" role="status"><LoaderCircle className="spin"/><div><strong>{active.phase}</strong><p>Keep this thread open for processing steps and saved outputs. Hosted work continues if you close it; returning resumes synchronization.</p></div><button className="text-btn" onClick={()=>task("cancel",async()=>{await request(`/api/jobs/${active.id}`,json("POST",{action:"cancel"}));await refresh(p!.id)})}>Cancel</button></div>}{latest?.kind===kind&&latest.status==="failed"&&<div className="error-banner" role="alert"><AlertCircle/><div><strong>This step needs another try</strong><p>{latest.error}</p></div><button disabled={!!busy} onClick={()=>task("retry",async()=>{await request(`/api/jobs/${latest.id}`,json("POST",{action:"retry"}));await refresh(p!.id)})}>Retry</button></div>}</>;
 return <div className="studio thread-studio"><Toaster position="bottom-center" richColors/><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><House size={22}/></span><span>walkthrough<span className="brand-sub">INSPECTION STUDIO</span></span></a><div className="top-actions"><span className="private-label"><ShieldCheck size={15}/>{account.username}</span><button className="btn small" onClick={()=>setNewOpen(true)} disabled={!!busy||uploadPct!==null||notesDirty.current}><Plus/><span>New inspection</span></button><button className="text-btn" onClick={onLogout} disabled={!!busy||uploadPct!==null||notesDirty.current}>Sign out</button></div></header>
 <main className="thread-workspace">{!online&&<div className="offline-banner" role="status"><AlertCircle size={18}/><span>You’re offline. Reconnect to save, analyze or export. Keep this screen open to retain unsaved text; choose the same video to resume an interrupted upload.</span></div>}{loadError&&<div className="error-banner" role="alert"><AlertCircle/>{loadError}<button onClick={()=>task("load",async()=>{setLoadError("");const list=await loadList();if(selected)await refresh(selected);else if(list[0])setSelected(list[0].id)})}>Retry</button></div>}
 {loading&&!p?<div className="loading-state"><LoaderCircle className="spin"/><p>Opening your inspections…</p></div>:!p?<section className="intake"><span className="eyebrow">START WITH THE WALKTHROUGH</span><h1>Let’s inspect the evidence.</h1><p>Upload your footage, add context, then review each observation in one conversation.</p><div className="new-card form-stack">{createFields}</div><p className="intake-footnote"><ShieldCheck size={15}/>Your approval determines what reaches the homeowner.</p></section>:<>
 <div className="thread-heading"><div className="project-picker"><FolderOpen size={15}/><Select value={selected||undefined} disabled={!!busy||uploadPct!==null||notesDirty.current} onValueChange={setSelected}><SelectTrigger className="project-select" aria-label="Choose inspection"><SelectValue/></SelectTrigger><SelectContent>{projects.map(q=><SelectItem key={q.id} value={q.id}>{q.address}</SelectItem>)}</SelectContent></Select><span className="revision">REV {p.revision}</span></div><h1>{p.address}</h1><p>{p.date}{p.inspector?` · ${p.inspector}`:""}<span className="thread-private"><ShieldCheck size={13}/>Private inspection</span></p></div>
 <div className="conversation"><article className="thread-card source-card"><div className="thread-label"><span className="thread-avatar inspector-avatar">{(p.inspector||account.username).slice(0,1).toUpperCase()}</span><div><strong>Your walkthrough</strong><small>Footage and inspector context</small></div></div>{p.video?.status!=="ready"?<div className={`upload-zone ${drag?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(uploadPct===null)void upload(e.dataTransfer.files[0])}}><Upload size={28}/><h2>{uploadPct!==null?"Saving your walkthrough…":p.video?"Resume your upload":"Add the walkthrough"}</h2><p>{p.video?"Choose the same video to continue from the saved parts.":"Spoken notes are optional. Add more context below at any time."}</p><input ref={fileInput} type="file" className="sr-only" accept="video/mp4,video/quicktime,video/webm" onChange={e=>upload(e.target.files?.[0])} aria-label="Choose walkthrough video"/>{uploadPct===null?<button className="btn primary" onClick={()=>fileInput.current?.click()}><Upload/>Choose video</button>:<div className="upload-progress"><Progress value={uploadPct}/><span>{uploadPct}% uploaded</span></div>}<small>Up to 1 GiB and 90 minutes</small></div>:<details className="source-attachment"><summary><Film/><span>{p.video.name}<small>{size(p.video.size)} · {p.video.duration?timestamp(p.video.duration):"Saved source video"}</small></span><Play size={17}/></summary><video controls playsInline preload="metadata" src={`/api/projects/${p.id}/upload`}/></details>}
 <details className="context-details" open={!p.video||!p.coverage}><summary>Inspector details{p.notes?" · Saved":" · Optional"}</summary><label className="sr-only" htmlFor="notes">Inspector details</label><textarea id="notes" disabled={!!busy} value={notes} onChange={e=>{notesDirty.current=true;setNotes(e.target.value)}} placeholder="Measurements, inspection conditions, rooms visited, concerns…" rows={3} maxLength={15000}/><div className="context-actions"><label className="inline-toggle"><Switch checked={p.narration} aria-label="Use spoken narration" disabled={!!active||!!busy} onCheckedChange={v=>task("narration",async()=>{await request(`/api/projects/${p.id}`,json("PATCH",{revision:p.revision,narration:v}));await refresh(p.id)})}/><span>Use spoken notes</span></label><button className="btn small" onClick={saveNotes} disabled={!!busy||notes===p.notes}><Check/>Save details</button></div></details>{p.video?.status==="ready"&&!p.coverage&&<button className="text-btn" onClick={()=>setEdit(initialFinding())} disabled={!!active||!!busy}><Plus/>Add an inspector observation</button>}</article>
 {!runtime?.configured&&<div className="notice"><Settings2/><span>AI is not connected. Configure the server API key to analyze footage. Your video and details can still be saved.</span></div>}
 {p.video?.status==="ready"&&!p.coverage&&!active&&<article className="thread-card assistant-card"><div className="thread-label"><span className="thread-avatar"><House size={17}/></span><strong>Ready for a closer look</strong></div><p>I’ll review sampled video evidence and your notes, then bring back tentative observations for your approval.</p><button className="btn primary" disabled={!!busy||!runtime?.configured} onClick={()=>startJob("analysis")}><Film/>Analyze walkthrough</button></article>}
 {progress("analysis")}
 {p.coverage&&<article className="thread-card assistant-card"><div className="thread-label"><span className="thread-avatar"><House size={17}/></span><strong>Let’s review the evidence</strong></div><p>{p.findings.length?`${pending.length} awaiting review · ${approved.length} approved. Check each timestamp and adjust the wording before approval.`:p.lastAnalysisJobId?"No supported observations were returned. This does not establish that the property has no issues. Add your own observation or tell me what needs a closer look.":"The video evidence and spoken notes are prepared. Findings will appear after analysis completes successfully."}</p><details className="scope-details"><summary>What was reviewed</summary><p>{p.coverage}</p>{p.transcript&&<details><summary>Spoken notes transcript</summary><pre>{p.transcript}</pre></details>}</details><div className="inline-actions"><button className="btn small" onClick={()=>setEdit(initialFinding())} disabled={!!busy||!!active}><Plus/>Add observation</button><button className="text-btn" onClick={()=>startJob("analysis")} disabled={!!busy||!!active}>Analyze again</button></div></article>}
 {p.findings.map(f=><article className={`finding-card ${f.decision}`} key={f.id}><div className="finding-head"><span className={`severity ${f.severity}`}>{f.severity}</span><button className="evidence-time" onClick={()=>seek(f.timestamp)}><Play size={12}/>{timestamp(f.timestamp)}–{timestamp(f.endTimestamp)}</button></div><h3>{f.title}</h3><p className="finding-location">{f.location}</p><p>{f.observation}</p><div className="evidence-note"><Film size={16}/><p>{f.evidence}</p></div><details className="finding-explanation"><summary>Why it matters & next steps</summary><p>{f.whyItMatters}</p><p>{f.recommendation}</p><small>{f.confidence}</small></details><div className="finding-footer"><span className={`decision ${f.decision}`}>{f.decision==="approved"?<Check size={14}/>:f.decision==="dismissed"?<X size={14}/>:<Clock size={14}/>} {f.decision==="pending"?"Your review is needed":f.decision}</span><div><button className="text-btn" onClick={()=>setEdit({...f})} disabled={!!active}>Edit</button>{f.decision!=="dismissed"&&<button className="text-btn" disabled={!!busy||!!active} onClick={()=>saveFinding({...f,decision:"dismissed"})}>Dismiss</button>}{f.decision!=="approved"&&<button className="btn small primary" disabled={!!busy||!!active} onClick={()=>saveFinding({...f,decision:"approved"})}><Check/>Approve</button>}</div></div></article>)}
 {p.messages.map(m=><article className={`thread-message ${m.role}`} key={m.id}><div className="thread-label"><span className="thread-avatar">{m.role==="user"?<MessageSquare size={16}/>:<House size={16}/>}</span><strong>{m.role==="user"?"You":"Review assistant"}</strong></div><p>{m.text}</p></article>)}{progress("chat")}
 {p.video?.status==="ready"&&<AerialCard project={p} disabled={!!active||!!busy} onSaved={()=>refresh(p.id)} onError={message=>toast.error(message)}/>}
 {approved.length>0&&<article className="thread-card delivery-thread"><div className="thread-label"><span className="thread-avatar"><Scissors size={17}/></span><strong>Prepare the homeowner package</strong></div><p>A narrated recap and written report, both based on the same {approved.length} approved observation{approved.length===1?"":"s"}.</p>{pending.length>0?<div className="notice"><Clock/><span>Approve or dismiss {pending.length} remaining suggestion{pending.length===1?"":"s"} first.</span></div>:<><div className="narration-review">{narration?<><details><summary>Review the narration script<span>Cedar · AI-generated voice</span></summary>{narration.scenes.map((s,i)=><div key={s.key}><strong>{i===0?"Opening":i===narration.scenes.length-1?"Closing":`Observation ${i}`}</strong><p>{s.text}</p></div>)}</details><label className="voice-approval"><Checkbox checked={approvedHash===narration.hash} onCheckedChange={v=>setApprovedHash(v===true?narration.hash:"")} aria-label="Approve narration script"/><span>I reviewed and approve this exact script for the homeowner.</span></label></>:<p>Preparing the current script…</p>}</div><button className="btn primary" disabled={!narration||approvedHash!==narration.hash||!!active||!!busy||!runtime?.configured} onClick={()=>startJob("export")}><Scissors/>Generate report & recap</button><small className="delivery-note">AI-generated voice · Source audio omitted · Selected footage, annotations and explanations</small></>}{progress("export")}</article>}
 {files.length>0&&<article className="thread-card output-list"><div className="thread-label"><span className="thread-avatar"><CheckCheck size={18}/></span><div><strong>Your package is ready</strong><small>Saved outputs remain tied to their approved revision.</small></div></div>{files.map(f=><div className="output-row" key={f.id}>{f.mime.startsWith("video")?<Film/>:<FileText/>}<div><strong>{f.name}</strong><span>Revision {f.revision} · {size(f.size)}{f.revision!==p.revision?" · Earlier approved revision":""}</span></div>{f.mime.startsWith("video")&&<button className="btn small" onClick={()=>setPreviewFile(`/api/projects/${p.id}/files/${f.id}`)}><Play/>Preview</button>}<a className="btn small" href={`/api/projects/${p.id}/files/${f.id}?download=1`} aria-label={`Download ${f.name}`}><Download/></a></div>)}</article>}
 </div><div className="thread-composer-wrap"><form className="thread-composer" onSubmit={e=>{e.preventDefault();void sendContext()}}><label htmlFor="chat" className="sr-only">Message review assistant</label><textarea id="chat" disabled={!!busy} value={chat} onChange={e=>setChat(e.target.value)} placeholder={p.coverage?"Ask about a finding, add context, or clarify what comes next…":"Add context for the inspection…"} rows={2} maxLength={8000}/><div><span>{active?"Processing is in progress…":p.coverage?"Your judgment stays final":"Saved as inspector context before analysis"}</span><button className="send-btn" disabled={!chat.trim()||!!active||!!busy||(!!p.coverage&&!runtime?.configured)} aria-label="Send message"><Send size={18}/></button></div></form><p className="composer-note">Selected video evidence supports your inspection. It does not establish an exhaustive inspection or certified diagnosis.</p></div>
 </>}
 </main>
 <Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Start an inspection</DialogTitle><DialogDescription>Your footage, context and review stay in one conversation.</DialogDescription></DialogHeader><div className="form-stack">{createFields}</div></DialogContent></Dialog>
 <Dialog open={evidenceTime!==null} onOpenChange={v=>!v&&setEvidenceTime(null)}><DialogContent className="app-dialog video-dialog"><DialogHeader><DialogTitle>Source evidence · {timestamp(evidenceTime||0)}</DialogTitle><DialogDescription>Check the original footage before approving this observation.</DialogDescription></DialogHeader>{p&&evidenceTime!==null&&<video controls autoPlay playsInline src={`/api/projects/${p.id}/upload`} onLoadedMetadata={e=>{e.currentTarget.currentTime=evidenceTime;void e.currentTarget.play().catch(()=>{})}}/>}</DialogContent></Dialog>
 <Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><DialogContent className="app-dialog finding-dialog"><DialogHeader><DialogTitle>Review observation</DialogTitle><DialogDescription>Check the evidence and wording before approving it for the homeowner.</DialogDescription></DialogHeader>{edit&&<div className="form-stack"><label>Title<input value={edit.title} maxLength={120} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><div className="form-grid"><label>Location<input value={edit.location} maxLength={120} onChange={e=>setEdit({...edit,location:e.target.value})}/></label><label>Priority<Select value={edit.severity} onValueChange={v=>setEdit({...edit,severity:v as Finding['severity']})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="attention">Attention</SelectItem><SelectItem value="maintenance">Maintenance</SelectItem><SelectItem value="information">Information</SelectItem></SelectContent></Select></label></div><div className="form-grid"><label>Evidence starts (seconds)<input type="number" min={0} max={5400} value={edit.timestamp} onChange={e=>setEdit({...edit,timestamp:Number(e.target.value)})}/></label><label>Evidence ends (seconds)<input type="number" min={0} max={5400} value={edit.endTimestamp} onChange={e=>setEdit({...edit,endTimestamp:Number(e.target.value)})}/></label></div>{([['observation','Observation'],['evidence','What the video shows'],['whyItMatters','Why it matters'],['recommendation','Recommended follow-up']] as const).map(([key,label])=><label key={key}>{label}<textarea value={edit[key]} maxLength={key==='observation'?2000:1000} rows={3} onChange={e=>setEdit({...edit,[key]:e.target.value,decision:"pending"})}/></label>)}<div className="narration-row"><div><strong>Include an explanatory diagram</strong><p>A simple observation → possible effect → next step flow.</p></div><Switch checked={!!edit.diagram} aria-label="Include explanatory diagram" onCheckedChange={v=>setEdit({...edit,diagram:v?{cause:"",effect:"",action:""}:null,decision:"pending"})}/></div>{edit.diagram&&(['cause','effect','action'] as const).map((key,i)=><label key={key}>{['Observation','Possible effect','Next step'][i]}<input value={edit.diagram![key]} maxLength={120} onChange={e=>setEdit({...edit,diagram:{...edit.diagram!,[key]:e.target.value},decision:"pending"})}/></label>)}<div className="dialog-actions"><button className="btn" disabled={!!busy||!edit.title||!edit.observation||!edit.evidence} onClick={()=>saveFinding({...edit,decision:"pending"})}>Save for review</button><button className="btn primary" disabled={!!busy||!edit.title||!edit.observation||!edit.evidence} onClick={()=>saveFinding({...edit,decision:"approved"})}><Check/>Approve finding</button></div></div>}</DialogContent></Dialog>
 <Dialog open={!!previewFile} onOpenChange={v=>!v&&setPreviewFile(null)}><DialogContent className="app-dialog video-dialog"><DialogHeader><DialogTitle>Homeowner recap</DialogTitle><DialogDescription>Generated from the approved report revision.</DialogDescription></DialogHeader>{previewFile&&<video controls autoPlay playsInline src={previewFile}/>}</DialogContent></Dialog>
 </div>
}

export default function App(){return <AuthGate>{(account,logout)=><InspectionStudio key={account.id} account={account} onLogout={logout}/>}</AuthGate>}
